-- MySQL Script generated by MySQL Workbench
-- Thu Apr 23 11:26:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_liquidacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_liquidacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_liquidacion` DEFAULT CHARACTER SET utf8 ;
USE `db_liquidacion` ;

-- -----------------------------------------------------
-- Table `db_liquidacion`.`productos_fijo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_liquidacion`.`productos_fijo` (
  `codigo_pro` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(80) NOT NULL,
  `marca` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_liquidacion`.`imp_calculado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_liquidacion`.`imp_calculado` (
  `id_imp_cal` INT NOT NULL AUTO_INCREMENT,
  `codigo_pro` VARCHAR(80) NOT NULL,
  `cantidad` INT NOT NULL,
  `descripcion` VARCHAR(70) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `dai` DOUBLE NOT NULL,
  `isc` DOUBLE NOT NULL,
  `tf` DOUBLE NOT NULL,
  `gato_agencia` DOUBLE NOT NULL,
  `costo_total` DOUBLE NOT NULL,
  `costo_unitario` DOUBLE NOT NULL,
  `minorista` DOUBLE NOT NULL,
  `licitacion` DOUBLE NOT NULL,
  `mayorista` DOUBLE NOT NULL,
  `pyme` DOUBLE NOT NULL,
  `publico` DOUBLE NOT NULL,
  `enemigo` DOUBLE NOT NULL,
  `malo` DOUBLE NOT NULL,
  `precio` DOUBLE NOT NULL,
  `p_cif` DOUBLE NOT NULL,
  PRIMARY KEY (`id_imp_cal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_liquidacion`.`imp_pagados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_liquidacion`.`imp_pagados` (
  `id_imp_pagados` INT NOT NULL AUTO_INCREMENT,
  `dgi` DOUBLE NOT NULL,
  `tf` DOUBLE NOT NULL,
  `isc` DOUBLE NOT NULL,
  `dai` DOUBLE NOT NULL,
  `p_cif_ingre` DOUBLE NOT NULL,
  `flete_final` DOUBLE NOT NULL,
  `flete_usa` DOUBLE NOT NULL,
  `agencia` DOUBLE NOT NULL,
  `timbres_fis` DOUBLE NOT NULL,
  `impuesto_selec` DOUBLE NOT NULL,
  `derecho_arance` DOUBLE NOT NULL,
  `gto_agenci` DOUBLE NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_imp_pagados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_liquidacion`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_liquidacion`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `codigo_pro` VARCHAR(65) NOT NULL,
  `cantidad` INT NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `p_cif` DOUBLE NOT NULL,
  PRIMARY KEY (`idproductos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
